server:
  port: 8183

app:
  sp1_seikyu:
    billing_principal_amount: 50000
    billing_interest_amount: 0
    deposit_principal_amount: 0
    deposit_interest_amount: 0
  sprv_seikyu:
    billing_principal_amount: 30000
    billing_interest_amount: 369
    deposit_principal_amount: 0
    deposit_interest_amount: 0
  sp1_zandaka:
    principal_amount: 50000
    interest_amount: 0
  sprv_zandaka:
    principal_amount: 30000
    interest_amount: 0
